# NLTK

#### Install NLTK

In [ ]:
!pip install nltk

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


#### Download models or corpora

In [ ]:
!python -m nltk.downloader

/usr/lib/python3.9/runpy.py:127: RuntimeWarning: 'nltk.downloader' found in sys.modules after import of package 'nltk', but prior to execution of 'nltk.downloader'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
NLTK Downloader
---------------------------------------------------------------------------
    d) Download   l) List    u) Update   c) Config   h) Help   q) Quit
---------------------------------------------------------------------------
Downloader> q'
Command "q'" unrecognized

---------------------------------------------------------------------------
    d) Download   l) List    u) Update   c) Config   h) Help   q) Quit
---------------------------------------------------------------------------
Downloader> q


#### Import and use

In [ ]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [ ]:
tweet = "@elonmusk digital currency is the future! :) #dogecoin"

In [ ]:
query = 'future'

In [ ]:
tweet.find(query) # Not great solution for searching for a term... (What if I looked for "dig"?)

34

#### Tokenization

In [ ]:
tweet.split() # Also not great...

['@elonmusk', 'digital', 'currency', 'is', 'the', 'future!', ':)', '#dogecoin']

In [ ]:
["future" in tweet.split()] # Also not great...

[False]

In [ ]:
nltk.word_tokenize(tweet) # Bingo!

['@',
 'elonmusk',
 'digital',
 'currency',
 'is',
 'the',
 'future',
 '!',
 ':',
 ')',
 '#',
 'dogecoin']

In [ ]:
[query in nltk.word_tokenize(tweet)] # Bingo!


[True]

#### More options in customizing your tokenizer

In [ ]:
nltk.word_tokenize(tweet, language='spanish')

['@',
 'elonmusk',
 'digital',
 'currency',
 'is',
 'the',
 'future',
 '!',
 ':',
 ')',
 '#',
 'dogecoin']

In [ ]:
from nltk.tokenize import RegexpTokenizer
custom_tokenizer = RegexpTokenizer('[a-zA-Z0-9]+', discard_empty=True)

In [ ]:
custom_tokenizer.tokenize(tweet)

['elonmusk', 'digital', 'currency', 'is', 'the', 'future', 'dogecoin']

In [ ]:
from nltk.tokenize import TweetTokenizer
tweet_tokenizer = TweetTokenizer(strip_handles=True, reduce_len=True)

In [ ]:
tweet_tokenizer.tokenize(tweet)

['digital', 'currency', 'is', 'the', 'future', '!', ':)', '#dogecoin']

In [ ]:
from nltk.tokenize import MWETokenizer
mwe = MWETokenizer()
mwe.add_mwe(('digital', 'currency'))
mwe.tokenize(tweet_tokenizer.tokenize(tweet))

['digital_currency', 'is', 'the', 'future', '!', ':)', '#dogecoin']

In [ ]:
query = 'digital'
query in mwe.tokenize(tweet_tokenizer.tokenize(tweet))

False

### Normalization

In [ ]:
tweet.lower()

'@elonmusk digital currency is the future! :) #dogecoin'

In [ ]:
import re
import string

def normalize_tokens(tokenized_text):
    # Lowercase
    tokens = [t.lower() for t in tokenized_text]
    # Remove hashtags
    tokens = [t for t in tokens if not t.startswith('#')]
    # Remove punctuation
    tokens = [t for t in tokens if t not in string.punctuation]
    # Keep only letters
#     tokens = [t for t in tokens if re.match('^[a-z]+$', t)]
    # Normalize characters
#     tokens = [re.sub('á', 'a', t) for t in tokens]
    tokens = [re.sub('ă', 'a', t) for t in tokens]

    return tokens

In [ ]:
romanian_query = 'monedă digitală'
normalize_tokens(tweet_tokenizer.tokenize(romanian_query))

['moneda', 'digitala']

In [ ]:
!pip install unidecode

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import unidecode
unidecode.unidecode(romanian_query)

'moneda digitala'

In [ ]:
normalized_tweet = normalize_tokens(tweet_tokenizer.tokenize(tweet))
print(normalized_tweet)

['digital', 'currency', 'is', 'the', 'future', ':)']


#### Stopwords

In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
from nltk.corpus import stopwords
stopwords.words('romanian')

['a',
 'abia',
 'acea',
 'aceasta',
 'această',
 'aceea',
 'aceeasi',
 'acei',
 'aceia',
 'acel',
 'acela',
 'acelasi',
 'acele',
 'acelea',
 'acest',
 'acesta',
 'aceste',
 'acestea',
 'acestei',
 'acestia',
 'acestui',
 'aceşti',
 'aceştia',
 'adica',
 'ai',
 'aia',
 'aibă',
 'aici',
 'al',
 'ala',
 'ale',
 'alea',
 'alt',
 'alta',
 'altceva',
 'altcineva',
 'alte',
 'altfel',
 'alti',
 'altii',
 'altul',
 'am',
 'anume',
 'apoi',
 'ar',
 'are',
 'as',
 'asa',
 'asta',
 'astea',
 'astfel',
 'asupra',
 'atare',
 'atat',
 'atata',
 'atatea',
 'atatia',
 'ati',
 'atit',
 'atita',
 'atitea',
 'atitia',
 'atunci',
 'au',
 'avea',
 'avem',
 'aveţi',
 'avut',
 'aş',
 'aţi',
 'ba',
 'ca',
 'cam',
 'cand',
 'care',
 'careia',
 'carora',
 'caruia',
 'cat',
 'catre',
 'ce',
 'cea',
 'ceea',
 'cei',
 'ceilalti',
 'cel',
 'cele',
 'celor',
 'ceva',
 'chiar',
 'ci',
 'cind',
 'cine',
 'cineva',
 'cit',
 'cita',
 'cite',
 'citeva',
 'citi',
 'citiva',
 'cu',
 'cui',
 'cum',
 'cumva',
 'cât',
 'câte

In [ ]:
cleaned_tweet = [t for t in normalized_tweet if t not in stopwords.words("english")]
print(cleaned_tweet)

['digital', 'currency', 'future', ':)']


#### Stemming / Lemmatization


In [ ]:
from nltk.stem import PorterStemmer
from nltk.stem import SnowballStemmer
from nltk.stem import WordNetLemmatizer

In [ ]:
# WordNet and OpenMultilingualWordnet necessary for lemmatization
nltk.download('wordnet')
nltk.download('omw-1.4')


[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.


True

In [ ]:
stemmer = PorterStemmer()

[stemmer.stem(t) for t in normalized_tweet]

['digit', 'currenc', 'is', 'the', 'futur', ':)']

In [ ]:
stemmer = SnowballStemmer(language='english') # This one has support for Romanian too!

[stemmer.stem(t) for t in normalized_tweet]

['digit', 'currenc', 'is', 'the', 'futur', ':)']

In [ ]:
lemmatizer = WordNetLemmatizer() # Doesn't have support for Romanian ... see Spacy instead

[lemmatizer.lemmatize(t) for t in normalized_tweet]

['digital', 'currency', 'is', 'the', 'future', ':)']

#### Combine with part-of-speech tagging!

In [ ]:
# Trained tagger needed for POS-tagging:
nltk.download('averaged_perceptron_tagger')

nltk.pos_tag(normalized_tweet)

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!


[('digital', 'JJ'),
 ('currency', 'NN'),
 ('is', 'VBZ'),
 ('the', 'DT'),
 ('future', 'NN'),
 (':)', 'NN')]

In [ ]:

from nltk.corpus import wordnet as wn

tag_map = {'J': wn.ADJ, 'V': wn.VERB, 'R': wn.ADV, 'N': wn.NOUN}
def get_lemmas(tokenized_text):
    tagged_text = nltk.pos_tag(tokenized_text)
    return [lemmatizer.lemmatize(w, pos=tag_map.get(p[0], wn.NOUN)) for (w, p) in tagged_text]


In [ ]:
query = "digital currencies"
normalized_query = normalize_tokens(tweet_tokenizer.tokenize(query))
print(normalized_query)

['digital', 'currencies']


In [ ]:
lemmatized_tweet = get_lemmas(normalized_tweet)
lemmatized_query = get_lemmas(normalized_query)
print(lemmatized_tweet)
print(lemmatized_query)


['digital', 'currency', 'be', 'the', 'future', ':)']
['digital', 'currency']


In [ ]:
# Now we can properly match the two!

print(set(lemmatized_tweet).intersection(lemmatized_query))

{'currency', 'digital'}


#### Sentence segmentation

In [ ]:
query = "I am too fast. I am too furious."

In [ ]:
from nltk.tokenize import sent_tokenize

In [ ]:
sent_tokenize(query)

['I am too fast.', 'I am too furious.']

In [ ]:
spanish_tokenizer = nltk.data.load('tokenizers/punkt/PY3/spanish.pickle')
spanish_query = 'Soy muy rápido! Estoy muy furioso!'
spanish_tokenizer.tokenize(spanish_query)

['Soy muy rápido!', 'Estoy muy furioso!']

In [ ]:
sent_tokenize("J.K. Rowling is rich. I am not as rich as J.K.")

['J.K. Rowling is rich.', 'I am not as rich as J.K.']

In [ ]:
from nltk.tokenize import PunktSentenceTokenizer
PunktSentenceTokenizer??

## Spacy

In [ ]:
%%bash
pip install spacy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
!python -m spacy download en_core_web_sm

/usr/local/lib/python3.8/dist-packages/torch/cuda/__init__.py:497: UserWarning: Can't initialize NVML
  warnings.warn("Can't initialize NVML")
2023-01-30 17:12:09.837250: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 42.4 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')


#### Define the model

In [ ]:
import spacy


/usr/local/lib/python3.9/dist-packages/torch/cuda/__init__.py:497: UserWarning: Can't initialize NVML
  warnings.warn("Can't initialize NVML")


#### Process the texts

In [ ]:
nlp = spacy.load("en_core_web_sm")



In [ ]:
tweet = "@elonmusk digital currency is the future! :) #dogecoin"


In [ ]:
text = nlp(tweet)
for token in text:
    print(token.text, token.lemma_, token.pos_, token.tag_, token.dep_,
            token.shape_, token.is_alpha, token.is_stop)

@elonmusk @elonmusk PROPN NNP nmod @xxxx False False
digital digital ADJ JJ amod xxxx True False
currency currency NOUN NN nsubj xxxx True False
is be AUX VBZ ROOT xx True True
the the DET DT det xxx True True
future future NOUN NN attr xxxx True False
! ! PUNCT . punct ! False False
:) :) PUNCT NFP ROOT :) False False
# # SYM $ dep # False False
dogecoin dogecoin VERB VB ROOT xxxx True False


### Romanian example

Here we have support for Romanian for all preprocessing tasks!

In [ ]:
!python -m spacy download ro_core_news_sm   # Get Romanian model

/usr/local/lib/python3.9/dist-packages/torch/cuda/__init__.py:497: UserWarning: Can't initialize NVML
  warnings.warn("Can't initialize NVML")
2023-03-19 19:12:49.839927: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
2023-03-19 19:12:49.840022: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
2023-03-19 19:12:49.840037: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentione

In [ ]:
from spacy.lang.ro.examples import sentences 

nlp = spacy.load("ro_core_news_sm")
doc = nlp(sentences[0])
print(doc.text)
for token in doc:
    print(token.text, token.lemma_, token.pos_, token.dep_)

Apple plănuiește să cumpere o companie britanică pentru un miliard de dolari
Apple Apple PROPN nsubj
plănuiește plănuii AUX ROOT
să să PART mark
cumpere cumpăra AUX ccomp
o un DET det
companie companie NOUN obj
britanică britanic ADJ amod
pentru pentru ADP case
un un DET det
miliard miliard NUM obl
de de ADP case
dolari dolar NOUN nmod


# Numericalization

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

from nltk.tokenize import TweetTokenizer
from nltk.corpus import stopwords

import string

In [ ]:
# Very customizable:
CountVectorizer??

In [ ]:
corpus = [
 'This is the first document.',
 'This document is the second document.',
 'And this is the third one.',
 'Is this the first document?',
 '@user This one is a tweet #meta ;)' 
]

In [ ]:
vectorizer = CountVectorizer()


In [ ]:

X = vectorizer.fit_transform(corpus)
print(vectorizer.get_feature_names_out())

['and' 'document' 'first' 'is' 'meta' 'one' 'second' 'the' 'third' 'this'
 'tweet' 'user']


In [ ]:
print(X.toarray())


[[0 1 1 1 0 0 0 1 0 1 0 0]
 [0 2 0 1 0 0 1 1 0 1 0 0]
 [1 0 0 1 0 1 0 1 1 1 0 0]
 [0 1 1 1 0 0 0 1 0 1 0 0]
 [0 0 0 1 1 1 0 0 0 1 1 1]]


### Customizing the Vectorizer

In [ ]:
tokenizer = TweetTokenizer(preserve_case=False, strip_handles=True)
tokenize_funct = tokenizer.tokenize
nltk.download('stopwords')
word_blacklist = stopwords.words('english') + list(string.punctuation)
vectorizer_tweet = CountVectorizer(tokenizer=tokenize_funct, stop_words=word_blacklist)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [ ]:
X1 = vectorizer_tweet.fit_transform(corpus)
print(vectorizer_tweet.get_feature_names_out())

['#meta' ';)' 'document' 'first' 'one' 'second' 'third' 'tweet']


/usr/local/lib/python3.9/dist-packages/sklearn/feature_extraction/text.py:528: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(


In [ ]:
X1

<5x8 sparse matrix of type '<class 'numpy.int64'>'
	with 12 stored elements in Compressed Sparse Row format>

In [ ]:
vectorizer_tweet.transform([corpus[0]]).toarray()


array([[0, 0, 1, 1, 0, 0, 0, 0]])

In [ ]:
vectorizertfidf = TfidfVectorizer()
Xtfidf = vectorizertfidf.fit_transform(corpus)
print(vectorizertfidf.get_feature_names_out())

['and' 'document' 'first' 'is' 'meta' 'one' 'second' 'the' 'third' 'this'
 'tweet' 'user']


In [ ]:
Xtfidf.toarray()

array([[0.        , 0.48961805, 0.58983706, 0.34836727, 0.        ,
        0.        , 0.        , 0.41188214, 0.        , 0.34836727,
        0.        , 0.        ],
       [0.        , 0.70933829, 0.        , 0.25235002, 0.        ,
        0.        , 0.52958485, 0.29835887, 0.        , 0.25235002,
        0.        , 0.        ],
       [0.54054601, 0.        , 0.        , 0.25757307, 0.        ,
        0.43610912, 0.        , 0.3045342 , 0.54054601, 0.25757307,
        0.        , 0.        ],
       [0.        , 0.48961805, 0.58983706, 0.34836727, 0.        ,
        0.        , 0.        , 0.41188214, 0.        , 0.34836727,
        0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.23518498, 0.49356209,
        0.39820278, 0.        , 0.        , 0.        , 0.23518498,
        0.49356209, 0.49356209]])

Text is now vectorized and ready for machine learning!